"""fix error

Revision ID: 0263cd414265
Revises: 0b8c6fbe58a6
Create Date: 2024-12-04 10:49:11.407172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0263cd414265'
down_revision = '0b8c6fbe58a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_province', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_city', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_district', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_subdistrict', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('users_shop_id_fkey', type_='foreignkey')
        batch_op.drop_column('state')
        batch_op.drop_column('shop_id')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_shop_id_fkey', 'shop', ['shop_id'], ['shop_id'])
        batch_op.drop_column('address_subdistrict')
        batch_op.drop_column('address_district')
        batch_op.drop_column('address_city')
        batch_op.drop_column('address_province')

    # ### end Alembic commands ###
