"""remove unique product, variant name

Revision ID: 318ca571578a
Revises: 875eac04a1bc
Create Date: 2024-12-14 07:59:13.540007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318ca571578a'
down_revision = '875eac04a1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_product_name_key', type_='unique')

    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_constraint('variants_variant_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.create_unique_constraint('variants_variant_name_key', ['variant_name'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('products_product_name_key', ['product_name'])

    # ### end Alembic commands ###
