"""add image variant table

Revision ID: 581b626819c4
Revises: e86f85334d9c
Create Date: 2024-12-05 20:59:23.863164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581b626819c4'
down_revision = 'e86f85334d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_products', schema=None) as batch_op:
        batch_op.drop_constraint('image_products_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('image_products_product_id_fkey', 'products', ['product_id'], ['product_id'])

    # ### end Alembic commands ###
