"""add voucher table

Revision ID: 59ee782130ca
Revises: 1836f1383d32
Create Date: 2024-12-17 22:45:48.993756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ee782130ca'
down_revision = '1836f1383d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('voucher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_name', sa.String(length=120), nullable=False),
    sa.Column('voucher_type', sa.String(length=120), nullable=False),
    sa.Column('voucher_value', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voucher_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voucher')
    # ### end Alembic commands ###
