"""remove unique discount name

Revision ID: 875eac04a1bc
Revises: 98821e83410e
Create Date: 2024-12-12 17:05:50.619261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875eac04a1bc'
down_revision = '98821e83410e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.drop_constraint('discounts_discount_name_key', type_='unique')

    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=120),
               nullable=False,
               existing_server_default=sa.text("'kg'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=120),
               nullable=True,
               existing_server_default=sa.text("'kg'::character varying"))

    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.create_unique_constraint('discounts_discount_name_key', ['discount_name'])

    # ### end Alembic commands ###
