"""add image variant table2

Revision ID: 95d597d1e320
Revises: 581b626819c4
Create Date: 2024-12-05 21:02:04.429142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d597d1e320'
down_revision = '581b626819c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variants',
    sa.Column('variant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variant_name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('variant_id'),
    sa.UniqueConstraint('variant_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variants')
    # ### end Alembic commands ###
