"""add product table

Revision ID: 973d4b14b959
Revises: 4aacf01491af
Create Date: 2024-12-04 23:41:33.943894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973d4b14b959'
down_revision = '4aacf01491af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_constraint('shops_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_label', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('address_label')

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shops_user_id_fkey', 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
