"""change column variant3

Revision ID: 98821e83410e
Revises: 9914deacdf2c
Create Date: 2024-12-12 10:58:15.188806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98821e83410e'
down_revision = '9914deacdf2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=120), server_default='kg', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
