"""change column variant

Revision ID: 9914deacdf2c
Revises: e9e7b1c6ae0a
Create Date: 2024-12-12 10:39:59.907232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9914deacdf2c'
down_revision = 'e9e7b1c6ae0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
