"""add voucher id column in order table

Revision ID: c08290597b77
Revises: 59ee782130ca
Create Date: 2024-12-17 22:48:16.205817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08290597b77'
down_revision = '59ee782130ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'voucher', ['voucher_id'], ['voucher_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('voucher_id')

    # ### end Alembic commands ###
