"""add colummn shop

Revision ID: dde7a124514b
Revises: a30ee71f600c
Create Date: 2024-12-16 23:02:37.246919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde7a124514b'
down_revision = 'a30ee71f600c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('shop_phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('shop_zip_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('shop_zip_code')
        batch_op.drop_column('shop_phone_number')
        batch_op.drop_column('shop_email')

    # ### end Alembic commands ###
