"""add image table

Revision ID: e86f85334d9c
Revises: 5e0dfb5004fd
Create Date: 2024-12-05 18:58:29.685644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86f85334d9c'
down_revision = '5e0dfb5004fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_products',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_data', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_products')
    # ### end Alembic commands ###
