"""change column product and variante

Revision ID: e9e7b1c6ae0a
Revises: a83b67e30264
Create Date: 2024-12-12 10:37:47.768594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e7b1c6ae0a'
down_revision = 'a83b67e30264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sold', sa.Integer(), nullable=True))
        batch_op.drop_column('price')
        batch_op.drop_column('stock')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('sold')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
